### ISSUE TITLE
documents POSTed with type application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#16]
there are a number of tests that POST documents with the type application/x-www-form-urlencoded and expect a successful response. 

However: "If the document being posted or any existing document does not have a Content-Type of application/json, or if either document cannot be parsed as a JSON Object, the LRS MUST respond with HTTP status code 400 Bad Request, and MUST NOT update the target document as a result of the request."

Either use PUT, use application/json or expect 400 bad request.

**Comment by fugu13** [comment]
👍

**Comment by stevenvergenz** [comment]
Agreed: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#2.2.s8.b1

**Comment by stevenvergenz** [comment]
To clarify, are you talking about the actual Documents API, or using the word "documents" generally? Because the `application/x-www-form-urlencoded` MIME type is valid on the Statements API as an alternative to the GET syntax. https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#13-alternate-request-syntax

**Comment by garemoko** [comment]
The documents api
