### ISSUE TITLE
The LRS is not supposed to reject statements containing empty objects

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#27]
LRS formatting validation requirements are set out here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#lrs-requirements

There's a number of requirements in 'Conformance Requirements using Templating requirements' that go beyond the scope of this and require the LRS to reject statements that:
- ~~Use a number where a string is required (Watershed will convert these to strings and accept the statement)~~
- Contain empty objects

**Comment by fugu13** [comment]
> Use a number where a string is required (Watershed will convert these to strings and accept the statement)

While that isn't called out as a disallowed conversion in the spec, anywhere the spec requires a string it would be disallowed for an LRS to accept a JSON number (except in parameters, where there is no distinction other than processing between a string that happens to contain a number and number that is not a string). As the data requirements section states, that section isn't intended to be exhaustive on what it means to be data type compliant, but emphatic. Data types are required to be followed.

> Contain empty objects

That this is allowed has been discussed a number of times, and is written into the spec with a non-starred SHOULD NOT: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#requirements . Of course, any object that has required properties cannot be empty.

**Comment by garemoko** [comment]
> anywhere the spec requires a string it would be disallowed for an LRS to accept a JSON number

Certainly the LRP has to send a string, and arguably the statements the LRS returns have to contain a string, and Watershed will do that. I'll also agree that it's a good idea for an LRS to reject statements that use numbers where a string is required. 

But I'm not seeing in the spec that the LRS **MUST** to validate all data types, or even this particular case of a number being used where a string is required.

**Comment by fugu13** [comment]
If the LRS doesn't have to validate data types then there are huge swathes of conformance that can be ignored as they're predicated on the idea the LRS needs to validate data types. The idea the LRS doesn't is ridiculous -- the whole point of having clearly marked data types is so people validate them. As the intro to the data constraints section says (and did long before it was broken up as it is):

> All the properties used in Statements are restricted to certain types, and those types constrain the behavior of systems processing Statements.

and then under that

> The following requirements reiterate especially important requirements already included elsewhere, to emphasize, clarify, and provide implementation guidance.

That is, the type-related information below is calling out particular obvious type-related errors, not relating all possible errors.

Remember, the main point of this entire exercise is to guarantee as much as possible that statements successfully sent to one LRS can be successfully sent to other LRSs without changing them, modulo narrow issues related to permissions and the like. If an LRS can optionally validate types, that's right out the window -- now some LRSs will accept numbers where strings are and others won't.

And that's before we look for any other types that are stated but without a corresponding MUST to check that the value actually is that type -- which would be optional for LRSs under your proposed interpretation. Types have always been discussed as required to validate, with a narrow range of specific types (IRIs for example) called out for accepting slightly less stringent validation on the LRS due to the high complexity.

(And, as those fields aren't specifically called out as exceptions, you're violating the immutability rules by changing a number to a string when you accept them).

**Comment by garemoko** [comment]
Ok, you had me at immutability. 

I do think specifically calling out two examples of data types in what is otherwise a fairly generic list is unhelpful. Raised a spec issue for a suggested PR: https://github.com/adlnet/xAPI-Spec/issues/982

**Comment by garemoko** [comment]
This is still an issue. The test "An Activity Definition contains at least one of the following properties: name, description, type, moreInfo, interactionType, or extensions" should be modified such that an LRS which rejects statements containing an empty object should fail. The requirement not to use empty objects is a SHOULD NOT aimed at LRPs.

**Comment by bscSCORM** [comment]
This: https://github.com/adlnet/lrs-conformance-test-suite/issues/129 appears to be another instance of the test over-zealously expecting empty objects to fail as well.

**Comment by bscSCORM** [comment]
and this:
https://github.com/adlnet/lrs-conformance-test-suite/issues/128
