### ISSUE TITLE
lrstest site: Edits to company name?

### ISSUE THREAD

**Issue by milt** [adlnet-archive/grail-issue-tracker#71]
OK, last one from me today, I promise ;)

I don't seem to be able to edit the company name on the LRS test site (the one that is included in certs when issued). Editing the company name on the adopters site works as expected, but since the LRS Test company name is in the certs, it still gets displayed in the conformant LRS list, etc.
Can/will this be possible in the future? Not a huge deal, but I'd like to correct some capitalization.

Thanks to the whole ADL team for really excellent work here!

**Comment by rchadwic** [comment]
This is actually by design. You'll notice that if you update the title in the Adopter site, you'll get a little exclamation point  notifying the user that you've edited the product title from the title that was stored in the certificate. We made this decision because of past abuses where a single test result was  used to certify multiple products. So, to edit the official title that's in the cert, you'll need to create a new product record and rerun the tests. 

We might  be open to allowing editing of the product name in the future, but then we'll have to lock the name into the certificate when the cert is first generated.

**Comment by milt** [comment]
Just to clarify, I was referring to the company name, not the product name, but I guess if both are interned in the cert I get what you're saying.

We'll just swap out the product (and thus the company name) on a future update, or maybe just reincorporate to match the incorrect one 😜
